# Generated by Django 4.1 on 2023-11-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storeapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="wikipedia_url",
            field=models.URLField(
                default="https://en.wikipedia.org/wiki/Default_Page_URL"
            ),
        ),
    ]
